[postgres]
PASSWORD= "atlasmoth23"
DB_USER = "postgres"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "airbnb_kaggle"

[kaggle]
username = "harikrishnanp2551"
key = "5f0cf7dd9a182d4c8dd6346fb22cafd5"